In [1]:
from decision_model_functions import *

In [2]:
import pickle 

def save_to_file(objeto, nome_arquivo):
    with open(nome_arquivo, 'wb') as output:
        pickle.dump(objeto, output, pickle.HIGHEST_PROTOCOL)


def load_file(nome_arquivo):
    with open(nome_arquivo, 'rb') as input:
        objeto = pickle.load(input)
    return objeto

In [3]:
queue = load_file('./ANALYSE_DATA/fila_treino_104.0_1.pkl')

In [4]:
json_file = open("./Action_Encoded_Model/modelo_outrun.json", 'r')
loaded_model_json = json_file.read()
json_file.close()
model = tf.keras.models.model_from_json(loaded_model_json)
model.load_weights("./Action_Encoded_Model/modelo_outrun.hdf5")
print("Loaded model from disk")

Loaded model from disk


In [5]:
#for i in np.arange(5,len(queue)-5,1):
for i in np.arange(5,50,1):
    #print('Starting to organize data before training... Nº', i, 'of', len(queue),'samples.', end='\r')
    print(np.round( model.predict( np.expand_dims( model_capture_return_images( [ process_img(j[0][120:,60:270]) for j in queue[i-5:i]]) , axis=0 ) ), 2 ) , queue[i][1].argmax())

[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0.04  0.07]] 6
[[ 0.04 -0.01  0.   -0.01 -0.01  0.03  0.8   0.14  0.14 -0.03 -0