In [2]:
import pandas as pd
import numpy as np
import cv2
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
import gc
import pytesseract
import glob
import re
from IPython.display import display, clear_output

In [3]:
def save_to_file(objeto, nome_arquivo):
    with open(nome_arquivo, 'wb') as output:
        pickle.dump(objeto, output, pickle.HIGHEST_PROTOCOL)


def load_file(nome_arquivo):
    with open(nome_arquivo, 'rb') as input:
        objeto = pickle.load(input)
    return objeto

In [4]:
list_of_files = glob.glob("../ANALYSE_DATA/*.pkl")

LOADING FILES AND WORKING WITH IT

8 px between each number

In [17]:
limit_numbers_1 = np.arange(136,200,8)
limit_numbers_2 = np.arange(144,208,8)

In [ ]:
vector_img = {}
for file in list_of_files:
    if 'fila_treino' in file:
        load = load_file(file)
        for i in load:
            for j in range(len(limit_numbers_1)):
                clear_output(wait=True)
                plt.imshow(i[0][15:24,136:200])
                display(plt.show())
                plt.imshow(i[0][15:24,limit_numbers_1[j]:limit_numbers_2[j]])
                display(plt.show())

                img = i[0].copy()

                ihash_1 = hash(img[15:24,limit_numbers_1[j]:limit_numbers_2[j]].tobytes())

                try:
                    display(print('valor 1 salvo:',vector_img[ihash_1][1]))
                except:
                    number = input('Digite para o valor 1: ')
                    vector_img[ihash_1] = (img[15:24,limit_numbers_1[j]:limit_numbers_2[j]].copy(),int(number))

In [25]:
save_to_file(vector_img, 'train_images_outrun_Score.pkl')

In [43]:
vector_img = load_file( 'train_images_outrun_Score.pkl')

In [44]:
vector_img[-2704009532181042674] = (vector_img[-2704009532181042674][0],2)

In [45]:
len(vector_img.keys())

1367

In [56]:
imgs = []
numbers = []
for i in list(vector_img.keys()):
    imgs.append(np.expand_dims(vector_img[i][0],axis=-1))
    numbers.append(vector_img[i][1])

In [58]:
pd.Series(numbers).value_counts(normalize=True)

0    0.302121
3    0.100219
2    0.095830
4    0.089978
7    0.073153
5    0.070958
1    0.070227
8    0.069495
6    0.068764
9    0.059254
dtype: float64

In [59]:
save_to_file(vector_img, 'finished_train_images_outrun_Score.pkl')

In [ ]:
limit_numbers_1 = np.arange(136,200,8)
limit_numbers_2 = np.arange(144,208,8)

In [62]:
np.arange(136,200,8)

array([136, 144, 152, 160, 168, 176, 184, 192])

In [61]:
np.arange(200,136,-8)

array([200, 192, 184, 176, 168, 160, 152, 144])

In [63]:
np.arange(192,128,-8)

array([192, 184, 176, 168, 160, 152, 144, 136])